---
- name: Handlers in Ansible
  hosts: all
  tasks:
   - name: Install Apache2
     apt:
      name: apache2
      state: present
     notify: check url response
   - name: Edit Index.html file
     copy:
      content: "Welcome to Hardeep's Page"
      dest: /var/www/html/index.html
     notify: Restart apache2
  handlers: 
   - name: Restart apache2
     service: 
      name: apache2
      state: restarted
   - name: check url response
     uri: 
      url: "{{item}}"
      status_code: 200
     with_items: 
       - http://172.31.13.247
       - http://172.31.4.17
