--- 
- name: Configuring apache2 on all nodes
  hosts: all
  tasks:
   - name : Configure apache2
     apt: 
      name: apache2
      state: present

   - name: Edit the Index.html file
     copy:
       content: "Welcome to Hardeep's Page"
       dest: /var/www/html/index.html
   - name: restart the apache services
     service:
      name: apache2
      state: restarted

   - name: check url response of the servers
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.13.247
      - http://172.31.4.17  


  
...
