---
- name: Installing s/w using PlayScope Variable
  hosts: all
  vars:
   - a: tomcat9
   - b: absent
   - c: yes
   - d: restarted
  tasks:
   - name: Install Tomcat
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
   - name: restart Tomcat
     service:
      name: "{{a}}"
      state: "{{d}}"
